/**
 * Routing files generated by `init`. Unlike the page templates in
 * `@answerable/templates`, these are configuration files (sitemap,
 * robots) and not "page" content — so they live in the CLI rather
 * than polluting the templates package.
 *
 * Both files use the `{{URL}}` token substituted at install time.
 */

export const SITEMAP_FILE_CONTENT = `import type { MetadataRoute } from 'next';
import { buildSitemap } from '@answerable/sitemap';

export default function sitemap(): MetadataRoute.Sitemap {
  return buildSitemap(
    [
      { path: '/' },
      { path: '/about' },
      { path: '/privacy' },
      { path: '/terms' },
      { path: '/faq' },
      { path: '/contact' },
    ],
    { baseUrl: '{{URL}}' },
  );
}
`;

export const ROBOTS_FILE_CONTENT = `import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: { userAgent: '*', allow: '/' },
    sitemap: '{{URL}}/sitemap.xml',
  };
}
`;
