import type { Command } from 'commander';

export type SupportedFramework = 'next';

const SUPPORTED_FRAMEWORKS: ReadonlyArray<SupportedFramework> = ['next'];

export interface InitAnalyticsCommandOptions {
  readonly siteId: string;
  readonly framework?: string;
  readonly appUrl?: string;
}

export interface InitAnalyticsCommandResult {
  readonly stdout: string;
  readonly exitCode: number;
  readonly error?: string;
}

const DEFAULT_APP_URL = 'https://app.answerfox.dev';

/**
 * Pure, testable runner for `answerfox init-analytics`.
 *
 * Prints a ready-to-use server-side analytics integration snippet for
 * the requested framework. Never embeds the ingest token — the
 * generated code reads it from an env var at runtime. This matches
 * the dashboard's mint-once disclosure model: the CLI cannot leak
 * what it does not know.
 *
 * Exit codes:
 * - 0: snippet rendered
 * - 2: bad arguments (missing siteId, unknown framework, malformed
 *      siteId)
 */
export function runInitAnalyticsCommand(
  opts: InitAnalyticsCommandOptions,
): InitAnalyticsCommandResult {
  const siteId = opts.siteId.trim();
  if (siteId.length === 0) {
    return { stdout: '', exitCode: 2, error: '--site-id is required.' };
  }
  // siteId is always a UUID v4 in our DB. Reject anything that obviously
  // isn't so users don't ship a bogus middleware.
  if (
    !/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(siteId)
  ) {
    return {
      stdout: '',
      exitCode: 2,
      error: 'Invalid --site-id. Expected a UUID (look in the dashboard URL after /sites/).',
    };
  }

  const framework = (opts.framework ?? 'next') as SupportedFramework;
  if (!SUPPORTED_FRAMEWORKS.includes(framework)) {
    return {
      stdout: '',
      exitCode: 2,
      error: `Unsupported --framework "${framework}". Supported: ${SUPPORTED_FRAMEWORKS.join(', ')}.`,
    };
  }

  const appUrl = (opts.appUrl ?? DEFAULT_APP_URL).replace(/\/+$/, '');

  switch (framework) {
    case 'next':
      return { stdout: renderNextMiddleware({ siteId, appUrl }), exitCode: 0 };
  }
}

function renderNextMiddleware({ siteId, appUrl }: { siteId: string; appUrl: string }): string {
  return [
    '// Generated by `answerfox init-analytics`. Save to middleware.ts at the',
    '// root of your Next.js app. Set ANSWERFOX_INGEST_TOKEN in your env.',
    "// Mint the token from the dashboard's Analytics integration card.",
    '',
    "import { NextResponse } from 'next/server';",
    "import type { NextRequest } from 'next/server';",
    '',
    `const INGEST_URL = '${appUrl}/api/track/visit';`,
    `const SITE_ID = '${siteId}';`,
    '',
    'export function middleware(req: NextRequest) {',
    '  const token = process.env.ANSWERFOX_INGEST_TOKEN;',
    '  if (token) {',
    '    // Fire and forget — never block the user request on this.',
    '    fetch(INGEST_URL, {',
    "      method: 'POST',",
    '      headers: {',
    '        Authorization: `Bearer ${token}`,',
    "        'Content-Type': 'application/json',",
    '      },',
    '      body: JSON.stringify({',
    '        siteId: SITE_ID,',
    "        userAgent: req.headers.get('user-agent') ?? '',",
    "        referrer: req.headers.get('referer'),",
    '        path: req.nextUrl.pathname,',
    '      }),',
    '    }).catch(() => {});',
    '  }',
    '  return NextResponse.next();',
    '}',
    '',
    'export const config = {',
    "  matcher: ['/((?!_next/|api/).*)'],",
    '};',
  ].join('\n');
}

export function registerInitAnalyticsCommand(program: Command): void {
  program
    .command('init-analytics')
    .description('Print a server-side analytics integration snippet for the chosen framework')
    .requiredOption('--site-id <uuid>', 'The site id from the dashboard URL')
    .option('--framework <name>', 'Framework target (currently: next)', 'next')
    .option('--app-url <url>', 'Override the Answerfox app URL', DEFAULT_APP_URL)
    .action((flags: Record<string, unknown>) => {
      const opts: InitAnalyticsCommandOptions = { siteId: String(flags.siteId ?? '') };
      if (typeof flags.framework === 'string') {
        Object.assign(opts, { framework: flags.framework });
      }
      if (typeof flags.appUrl === 'string') {
        Object.assign(opts, { appUrl: flags.appUrl });
      }
      const result = runInitAnalyticsCommand(opts);
      if (result.error !== undefined) {
        process.stderr.write(`${result.error}\n`);
      } else if (result.stdout.length > 0) {
        process.stdout.write(`${result.stdout}\n`);
      }
      process.exit(result.exitCode);
    });
}
