/**
 * Pure formatting + gating for the weekly readiness digest.
 *
 * No DB, no network, no `server-only` — all cheap to unit-test. The
 * cron route (`/api/cron/weekly-digest`) gathers the data, calls
 * `hasDigestContent` to skip empty users, then feeds the rest through
 * `weeklyDigestSubject` + `renderWeeklyDigestText` into the sender.
 */

export interface DigestSiteLine {
  readonly siteId: string;
  readonly name: string;
  readonly url: string;
  readonly currentScore: number;
  readonly band: string;
  /** Latest audit score from before the window opened, or null if the
   * site was first audited inside the window (nothing to compare to). */
  readonly previousScore: number | null;
}

export interface WeeklyDigestData {
  readonly userId: string;
  readonly email: string;
  readonly name: string | null;
  readonly sites: readonly DigestSiteLine[];
  /** Succeeded AI fixes generated by this user during the window. */
  readonly fixesGenerated: number;
  readonly windowStart: Date;
  readonly windowEnd: Date;
  /** Base URL for deep links (no trailing slash). */
  readonly appUrl: string;
}

/**
 * A digest is only worth sending if the user has at least one audited
 * site. An opted-in user with no audits gets nothing rather than an
 * empty email.
 */
export function hasDigestContent(data: WeeklyDigestData): boolean {
  return data.sites.length > 0;
}

/**
 * Signed week-over-week delta for one site. `+4`, `-3`, `even` when the
 * score held, or `new` when there's no prior-week baseline to diff.
 */
export function formatScoreDelta(currentScore: number, previousScore: number | null): string {
  if (previousScore === null) return 'new';
  const delta = currentScore - previousScore;
  if (delta === 0) return 'even';
  return delta > 0 ? `+${delta}` : `${delta}`;
}

/** Whole-number mean of the sites' current scores. */
export function averageScore(sites: readonly DigestSiteLine[]): number {
  if (sites.length === 0) return 0;
  const total = sites.reduce((sum, s) => sum + s.currentScore, 0);
  return Math.round(total / sites.length);
}

export function weeklyDigestSubject(data: WeeklyDigestData): string {
  const n = data.sites.length;
  const noun = n === 1 ? 'site' : 'sites';
  return `Answerfox · weekly digest: ${n} ${noun}, avg ${averageScore(data.sites)}/100`;
}

function formatWindow(start: Date, end: Date): string {
  const fmt = (d: Date) =>
    d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' });
  return `${fmt(start)} – ${fmt(end)}`;
}

/**
 * Plain-text body. Matches the score-drop alert's plain-text style
 * (no HTML template engine in this codebase). One block per site with
 * its current score, band, and week-over-week delta, then a footer
 * with the fixes generated this week and an unsubscribe pointer.
 */
export function renderWeeklyDigestText(data: WeeklyDigestData): string {
  const greeting = data.name && data.name.length > 0 ? `Hi ${data.name},` : 'Hi,';
  const lines: string[] = [
    greeting,
    '',
    `Here's how your ${data.sites.length === 1 ? 'site' : 'sites'} looked this week (${formatWindow(
      data.windowStart,
      data.windowEnd,
    )}).`,
    '',
  ];

  for (const site of data.sites) {
    const delta = formatScoreDelta(site.currentScore, site.previousScore);
    const deltaNote =
      delta === 'new'
        ? 'first audit this week'
        : delta === 'even'
          ? 'no change from last week'
          : `${delta} from last week`;
    lines.push(`${site.name} (${site.url})`);
    lines.push(`  ${site.currentScore}/100 · ${site.band} · ${deltaNote}`);
    lines.push(`  ${data.appUrl}/dashboard/sites/${site.siteId}`);
    lines.push('');
  }

  const fixNoun = data.fixesGenerated === 1 ? 'fix' : 'fixes';
  lines.push(`AI fixes generated this week: ${data.fixesGenerated} ${fixNoun}.`);
  lines.push('');
  lines.push('Turn this digest off anytime in Settings:');
  lines.push(`  ${data.appUrl}/dashboard/settings`);
  lines.push('');
  lines.push('— Answerfox');

  return lines.join('\n');
}
