import { createTwoFilesPatch } from 'diff';
import type { EditSet } from './types';

/**
 * Deterministic unified diff for a validated EditSet — generated by
 * code from before/after content, never by the model. This is what
 * the PR shows and what the dashboard renders.
 */
export function generateUnifiedDiff(
  repoFiles: ReadonlyMap<string, string>,
  editedFiles: ReadonlyMap<string, string>,
  editSet: EditSet,
): string {
  const parts: string[] = [];
  // Stable order: the EditSet's own path order, deduplicated.
  const seen = new Set<string>();
  for (const edit of editSet.edits) {
    if (seen.has(edit.path)) continue;
    seen.add(edit.path);
    const after = editedFiles.get(edit.path);
    if (after === undefined) continue;
    const before = repoFiles.get(edit.path) ?? '';
    const isNew = !repoFiles.has(edit.path);
    parts.push(
      createTwoFilesPatch(
        isNew ? '/dev/null' : `a/${edit.path}`,
        `b/${edit.path}`,
        before,
        after,
        undefined,
        undefined,
        { context: 3 },
      ),
    );
  }
  return parts.join('\n');
}
